# Form implementation generated from reading ui file '.\remote.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_remoteWindow(object):
    def setupUi(self, remoteWindow):
        remoteWindow.setObjectName("remoteWindow")
        remoteWindow.resize(208, 243)
        self.centralwidget = QtWidgets.QWidget(parent=remoteWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.powerButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.powerButton.setGeometry(QtCore.QRect(100, 10, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.powerButton.setFont(font)
        self.powerButton.setStyleSheet("background-color: red;")
        self.powerButton.setObjectName("powerButton")
        self.volumeUp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volumeUp.setGeometry(QtCore.QRect(10, 78, 31, 61))
        self.volumeUp.setObjectName("volumeUp")
        self.volumeDown = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volumeDown.setGeometry(QtCore.QRect(10, 158, 31, 61))
        self.volumeDown.setObjectName("volumeDown")
        self.channelDown = QtWidgets.QPushButton(parent=self.centralwidget)
        self.channelDown.setGeometry(QtCore.QRect(160, 158, 31, 61))
        self.channelDown.setObjectName("channelDown")
        self.channelUp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.channelUp.setGeometry(QtCore.QRect(160, 78, 31, 61))
        self.channelUp.setObjectName("channelUp")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 138, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 138, 47, 13))
        self.label_2.setObjectName("label_2")
        self.Mute = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Mute.setGeometry(QtCore.QRect(60, 130, 81, 31))
        self.Mute.setObjectName("Mute")
        remoteWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(remoteWindow)
        QtCore.QMetaObject.connectSlotsByName(remoteWindow)

    def retranslateUi(self, remoteWindow):
        _translate = QtCore.QCoreApplication.translate
        remoteWindow.setWindowTitle(_translate("remoteWindow", "Remote Window"))
        self.powerButton.setText(_translate("remoteWindow", "Power"))
        self.volumeUp.setText(_translate("remoteWindow", "+"))
        self.volumeDown.setText(_translate("remoteWindow", "-"))
        self.channelDown.setText(_translate("remoteWindow", "-"))
        self.channelUp.setText(_translate("remoteWindow", "+"))
        self.label.setText(_translate("remoteWindow", "Volume"))
        self.label_2.setText(_translate("remoteWindow", "Channel"))
        self.Mute.setText(_translate("remoteWindow", "Mute"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    remoteWindow = QtWidgets.QMainWindow()
    ui = Ui_remoteWindow()
    ui.setupUi(remoteWindow)
    remoteWindow.show()
    sys.exit(app.exec())
